### ISSUE TITLE
Vaadin Bakery App Starter for Flow and Spring not visible on IE11

### ISSUE THREAD

**Issue by gianluca-valentini** [vaadin/vaadin.com#44]
Hi,
after download demo code to try to use vaadin 10 `<vaadin.version>10.0.0.rc1</vaadin.version>`
the login page in not visible on Win7 using IE11, while using online demo it works fine.

![image](https://user-images.githubusercontent.com/3224592/41456849-0721b428-7082-11e8-82c1-a1ec5713bb43.png)

On the web demo we can see the application correctly

![image](https://user-images.githubusercontent.com/3224592/41456894-2d756386-7082-11e8-8d32-046a3ddc3e1c.png)

Is there something that I can do to fix this behavior?
On Firefox and Edge it is visible correctly

Gianluca

**Comment by paulroemer** [comment]
Hi Gianluca,

did you build in production mode? Especially the ES5 transpilation is needed to make IE11 work.

**Comment by gianluca-valentini** [comment]
Hi @paulroemer,
thanks for your answer. I just download and import project using Eclipse and run it. 

What I should do? Is not all configured by default in this demo project? 
Thanks
Gianluca

**Comment by paulroemer** [comment]
Sorry Gianluca,

I got distracted by other stuff, unfortunately. But to get an idea of what production mode means, please read https://vaadin.com/docs/v10/flow/production/tutorial-production-mode-basic.html

I am also sure that if you import the project in Eclipse the needed steps are _not_ executed. You will need to run the Maven Flow plugin and the easiest way to do it for bakery is by running `mvn jetty:run -Pproduction`

**Comment by gianluca-valentini** [comment]
Thanks.
I tried your suggestion adding `spring-boot:run -Pproduction` because I'm using the demo coming from spring boot.

Waiting a lot time  the result is the same for IE11
The same whete sad page :(

**Comment by paulroemer** [comment]
Damn, sorry for the wrong information: https://vaadin.com/docs/v10/bakeryflow/running-building-packaging.html

For bakery the option to activate production mode is different. 

>Building and running on production mode
>
>By default, building and running are made in 'development' mode. This is good while working on the app as the build/start time is shorter, but the app would not work in IE11. In order to use production mode, you need to add -Dvaadin.productionMode to build/run commands:
>
>build: mvn package -Dvaadin.productionMode run: mvn spring-boot:run -Dvaadin.productionMode
>
>Note that when you switch from one mode to another we should run mvn clean before running the other mode.

**Comment by paulroemer** [comment]
And do not forget to run `mvn clean` as mentioned.

**Comment by gianluca-valentini** [comment]
Hi @paulroemer 
thanks for your help. I execute `mvn clean` and then `spring-boot:run` adding -Dvaadin.productionMode as during build as in start command.

But the result is this an Internal Server Error
![image](https://user-images.githubusercontent.com/3224592/41539871-2a4781e6-730f-11e8-9ab4-9c41ccb127ee.png)


**Here some exception that I hope can help you to understand where I wrong**

```
2018-06-18 15:48:58.057 ERROR 8264 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcher]           : Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Servlet.init() for servlet [springServlet] threw exception] with root cause

java.lang.IllegalArgumentException: Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES6' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'flow-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'.
	at com.vaadin.flow.server.startup.BundleFilterInitializer.readBundleManifest(BundleFilterInitializer.java:76) ~[flow-server-1.0.0.rc1.jar:na]
	at com.vaadin.flow.server.startup.BundleFilterInitializer.addBundleFilterForBrowser(BundleFilterInitializer.java:67) ~[flow-server-1.0.0.rc1.jar:na]
	at com.vaadin.flow.server.startup.BundleFilterInitializer.serviceInit(BundleFilterInitializer.java:61) ~[flow-server-1.0.0.rc1.jar:na]
	at com.vaadin.flow.server.VaadinService.lambda$init$0(VaadinService.java:251) ~[flow-server-1.0.0.rc1.jar:na]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_77]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_77]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[na:1.8.0_77]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_77]
	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:251) ~[flow-server-1.0.0.rc1.jar:na]
	at com.vaadin.flow.spring.SpringServlet.createServletService(SpringServlet.java:56) ~[vaadin-spring-10.0.0.rc1.jar:na]
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:240) ~[flow-server-1.0.0.rc1.jar:na]
	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:76) ~[flow-server-1.0.0.rc1.jar:na]
```
[error.txt](https://github.com/vaadin/vaadin.com/files/2111489/error.txt)

**Comment by gianluca-valentini** [comment]
I tried to update the vaadin version from the declared `<vaadin.version>10.0.0.rc1</vaadin.version>` to
`<vaadin.version>10.0.0.rc5</vaadin.version>` but I have the same exception

**Comment by paulroemer** [comment]
I downloaded the bakery on my own and started the production mode. Because I am lacking of an IE11 it's impossible for me to reproduce the issue at all.

Anyway, I checked my local filesystem after running `mvn spring-boot:run -Dvaadin.productionMode` and I found the manifest your build is complaining about:
```
21:07:29 vaadin@tuxbook:~/tmp/bakery-app-starter-flow-spring> find . -name vaadin-flow-bundle-manifest.json
./src/main/webapp/frontend-es6/vaadin-flow-bundle-manifest.json
./src/main/webapp/frontend-es5/vaadin-flow-bundle-manifest.json
./target/bakery-app-starter-flow-spring-1.0-SNAPSHOT/frontend-es6/vaadin-flow-bundle-manifest.json
./target/bakery-app-starter-flow-spring-1.0-SNAPSHOT/frontend-es5/vaadin-flow-bundle-manifest.json
```

Can you check your local filesystem, too, and send me the output, please? It doubt it but maybe there is an issue with Windows builds we are faced with.

**Comment by gianluca-valentini** [comment]
Hi @paulroemer 
thanks a lot I found the error that caused the exception!
Using Eclipse I set `-Dvaadin.productionMode` in the maven build but as JVM arguments.

Adding it in the maven build configuration after `spring-boot:run` it start build the correct transpilation.

![image](https://user-images.githubusercontent.com/3224592/41561207-8406dcb0-7349-11e8-81fd-f816e71d6853.png)


Now it finally works fine

![image](https://user-images.githubusercontent.com/3224592/41561242-a17cbf76-7349-11e8-936a-e3b1254ddbb7.png)


THAKNS!!!

**Comment by alexei-28** [comment]
Vaadin 12.0.4. Gradle 5.1.

In my build gradle:

```
plugins {
    kotlin("jvm") version "1.3.20"
    id ("com.github.johnrengelman.shadow") version "4.0.3"
    id ("com.devsoap.vaadin-flow") version "1.0"
    id ("org.gretty") version "2.3.1"
}

val kotlinVersion = "1.3.20"
val jettyVersion = "9.4.14.v20181114"
val vaadinVersion = "12.0.4"
```
I have a Vaadin project and build it by Gradle. I create jar by pluggin shadowjar. And it's success build project.

In deploy folder I has:

```
folder: frontend
file: myproject.jar
file: logback.xml
```
To start project from console I use command:

`java -Dlogback.configurationFile=logback.xml -jar myproject.jar`

Nice. It's start success.

```
2019-03-13 10:36:35,747 3844 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@22a79b2f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-03-13 10:36:35,747 3844 [main] INFO  org.eclipse.jetty.server.Server - Started @4034ms
```
And I success open web page.

But I need to set production mode. So as result I run my project like this:

`java -Dvaadin.productionMode=true -Dlogback.configurationFile=logback.xml -jar myproject.jar`

And it start success. But when I try to open web page I get error:

```
2019-03-13 10:37:29,610 8468 [qtp495792375-15] WARN  o.e.j.s.handler.ContextHandler.ROOT - unavailable
java.lang.IllegalArgumentException: Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES6' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'vaadin-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'.
    at com.vaadin.flow.server.startup.BundleFilterFactory.readBundleManifest(BundleFilterFactory.java:89)
    at com.vaadin.flow.server.startup.BundleFilterFactory.createBundleFilterForBrowser(BundleFilterFactory.java:79)
    at com.vaadin.flow.server.startup.BundleFilterFactory.createFilters(BundleFilterFactory.java:70)
    at com.vaadin.flow.server.VaadinService.init(VaadinService.java:275)
    at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:201)
    at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:182)
    at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672)
    at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:521)
    at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:805)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:537)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:502)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
    at java.lang.Thread.run(Unknown Source)
2019-03-13 10:37:29,613 8471 [qtp495792375-15] WARN  o.eclipse.jetty.server.HttpChannel - /booking-v2
javax.servlet.ServletException: com.vaadin.flow.server.startup.ServletDeployer@a1f5568f==com.vaadin.flow.server.VaadinServlet,jsp=null,order=-1,inst=false,async=true
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:693)
    at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:521)
    at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:805)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:537)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:502)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES6' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'vaadin-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'.
    at com.vaadin.flow.server.startup.BundleFilterFactory.readBundleManifest(BundleFilterFactory.java:89)
    at com.vaadin.flow.server.startup.BundleFilterFactory.createBundleFilterForBrowser(BundleFilterFactory.java:79)
    at com.vaadin.flow.server.startup.BundleFilterFactory.createFilters(BundleFilterFactory.java:70)
    at com.vaadin.flow.server.VaadinService.init(VaadinService.java:275)
    at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:201)
    at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:182)
    at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672)
    ... 27 common frames omitted
```
